-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 22:41:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema game
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `game` DEFAULT CHARACTER SET utf8 ;
USE `game` ;

-- -----------------------------------------------------
-- Table `game`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`scores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` INT NOT NULL,
  `players_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scores_players_idx` (`players_id` ASC) VISIBLE,
  CONSTRAINT `fk_scores_players`
    FOREIGN KEY (`players_id`)
    REFERENCES `game`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `game`.`success`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`success` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `objectif` VARCHAR(255) NOT NULL,
  `img_path` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`.`advancements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `game`.`advancements` (
  `success_id` INT NOT NULL,
  `players_id` INT NOT NULL,
  PRIMARY KEY (`success_id`, `players_id`),
  INDEX `fk_Sucess_has_players_players1_idx` (`players_id` ASC) VISIBLE,
  INDEX `fk_Sucess_has_players_Sucess1_idx` (`success_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sucess_has_players_Sucess1`
    FOREIGN KEY (`success_id`)
    REFERENCES `game`.`success` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucess_has_players_players1`
    FOREIGN KEY (`players_id`)
    REFERENCES `game`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Insertition de succès
-- -----------------------------------------------------

INSERT INTO `success` (`id`, `name`, `description`, `objectif`, `img_path`) VALUES (NULL, 'Tourelle diff 1', 'Passer 50 vagues sans bouger', '50', 'full_heart.png');
INSERT INTO `success` (`id`, `name`, `description`, `objectif`, `img_path`) VALUES (NULL, 'Tourelle diff 2', 'Passer 100 vagues sans bouger', '100', 'full_heart.png');
INSERT INTO `success` (`id`, `name`, `description`, `objectif`, `img_path`) VALUES (NULL, 'Tourelle diff 3', 'Passer 150 vagues sans bouger', '150', 'full_heart.png');
INSERT INTO `success` (`id`, `name`, `description`, `objectif`, `img_path`) VALUES (NULL, 'Tourelle diff 4', 'Passer 200 vagues sans bouger', '200', 'full_heart.png');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
